/**
 * Shared TypeScript types for Design Studio
 * Used by frontend, backend, and database layers
 */

export type SourceType = 'FIGMA' | 'URL' | 'PROMPT'
export type IdeaStatus = 'DRAFT' | 'REVIEWED'
export type PromotionStatus = 'BUILDING' | 'PR_OPEN' | 'VERIFIED' | 'PUBLISHED' | 'FAILED'

/**
 * User entity - represents an authenticated user
 */
export interface User {
  id: string
  email: string
  name: string
  passwordHash: string
  createdAt: string // ISO 8601
}

/**
 * Project entity - a workspace for design-to-code workflows
 */
export interface Project {
  id: string
  name: string
  description?: string
  creatorId: string
  agentInstructions?: string
  githubRepoUrl?: string
  githubBranch: string
  githubAppInstallId?: string
  createdAt: string
}

/**
 * Figma connection - link to a Figma file for importing designs
 */
export interface FigmaConnection {
  id: string
  projectId: string
  displayName: string
  fileKey: string
  tokenArn: string // Secrets Manager ARN — token never stored in DynamoDB
}

/**
 * Idea entity - a design component to be generated or iterated
 */
export interface Idea {
  id: string
  projectId: string
  createdById: string
  createdByName: string // denormalized for display
  sourceType: SourceType
  sourceData: FigmaSource | UrlSource | PromptSource
  userPrompt?: string
  status: IdeaStatus
  createdAt: string
  updatedAt: string
}

/**
 * Design source from Figma - references a component in a Figma file
 */
export interface FigmaSource {
  type: 'FIGMA'
  connectionId: string
  nodeIds: string[]        // selected component or group node IDs
  componentNames: string[]
}

/**
 * Design source from URL - scraped from a web page
 */
export interface UrlSource {
  type: 'URL'
  url: string
  scrapedData?: string    // normalized output from importer agent
}

/**
 * Design source from user prompt - freeform text description
 */
export interface PromptSource {
  type: 'PROMPT'
  text: string
}

/**
 * Iteration entity - a generated component version from an idea
 */
export interface Iteration {
  id: string
  ideaId: string
  prompt: string
  generatedCode: string   // full component code from Bedrock
  previewUrl?: string     // S3 pre-signed URL of rendered snapshot
  createdAt: string
}

/**
 * Promotion entity - tracks a component's journey to production
 */
export interface Promotion {
  id: string
  ideaId: string
  promotedById: string
  promotedByName: string  // denormalized
  status: PromotionStatus
  prUrl?: string
  prNumber?: number
  publishedAt?: string
  createdAt: string
}

/**
 * ComponentSpec - normalized component specification from any source
 * Generated by Design Importer agent, consumed by Component Builder agent
 */
export interface ComponentSpec {
  name: string
  description: string
  props: ComponentProp[]
  variants?: ComponentVariant[]
  accessibility?: string
  designTokens?: Record<string, string>
}

export interface ComponentProp {
  name: string
  type: string
  required: boolean
  description?: string
  default?: unknown
}

export interface ComponentVariant {
  name: string
  description?: string
  props: Record<string, unknown>
}

/**
 * API request/response envelopes
 */
export interface ApiResponse<T> {
  data?: T
  error?: ApiError
  timestamp: string
}

export interface ApiError {
  code: string
  message: string
  details?: unknown
}

export interface AuthTokens {
  accessToken: string
  refreshToken: string
  expiresIn: number
}

export interface SessionData {
  userId: string
  email: string
  name: string
  expiresAt: string
}
